name: OIDC Test

on:
push:
branches:
- main

permissions:
id-token: write
contents: read

jobs:
test-oidc:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      role-to-assume: arn:aws:iam::945695383447:role/Role-4-Github
      aws-region: ap-south-1

  - name: Verify AWS Identity
    run: aws sts get-caller-identity